###
GET http://localhost:3001/api/blogs HTTP/1.0
accept: application/json

###

POST http://localhost:3001/api/blogs
content-type: application/json
accept: application/json
{
  "title": "Saunomista", 
  "author": "Kari Kiuas", 
  "url":"wikipedia.org", 
  "likes": 5
}
###
